name: '$(BuildID).$(date:yyMMdd)'

trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  webArtifactName: chia-wallet
  extArtifactName: chia-wallet-ext
  versionNumber: '0.1.$(Build.BuildNumber)'
  qaEnvironment: 'chiabee_wallet_qa'
  qaFtp: 'chiabee_wallet_dev_ftp'
  prEnvironment: 'chiabee_wallet_pr'
  prFtp: 'chiabee_wallet_pr_ftp'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - task: CmdLine@2
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        script: 'yarn'
      displayName: 'yarn'

    - task: CmdLine@2
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        script: |
          sed -i 's/0.0.0.0/$(versionNumber)/' .env.production
      displayName: 'set version'

    - task: CmdLine@2
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        script: 'yarn build'
      displayName: 'yarn build'

    - task: CmdLine@2
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        script: 'echo $(versionNumber)>$(Build.SourcesDirectory)/dist/web/version.txt'
      displayName: 'write version file'

    # - task: CmdLine@2
    #   inputs:
    #     workingDirectory: '$(Build.SourcesDirectory)'
    #     script: 'yarn build-ext'
    #   displayName: 'yarn build-ext'

    # - task: CmdLine@2
    #   inputs:
    #     workingDirectory: '$(Build.SourcesDirectory)'
    #     script: 'echo $(versionNumber)>$(Build.SourcesDirectory)/dist/ext/version.txt'
    #   displayName: 'write version file(ext)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/dist/web'
        ArtifactName: '$(webArtifactName)'
        publishLocation: 'Container'

    # - task: PublishBuildArtifacts@1
    #   inputs:
    #     PathtoPublish: '$(Build.SourcesDirectory)/dist/ext'
    #     ArtifactName: '$(extArtifactName)'
    #     publishLocation: 'Container'


- stage: pr
  displayName: pr
  condition: and(succeeded(), eq(variables['system.pullrequest.targetbranch'], 'refs/heads/master'))
  dependsOn:
  - build
  jobs:
  - deployment: prdeploy
    displayName: prDeploy
    timeoutInMinutes: 10
    cancelTimeoutInMinutes: 1
    environment: $(prEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: FtpUpload@2
            inputs:
              credentialsOption: 'serviceEndpoint'
              serverEndpoint: '$(prFtp)'
              rootDirectory: '$(Pipeline.Workspace)/$(webArtifactName)'
              filePatterns: '**'
              remoteDirectory: '/'
              clean: false
              cleanContents: false
              preservePaths: true
              trustSSL: false

- stage: qa
  displayName: qa
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn:
  - build
  jobs:
  - deployment: qadeploy
    displayName: qaDeploy
    timeoutInMinutes: 10
    cancelTimeoutInMinutes: 1
    environment: $(qaEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: FtpUpload@2
            inputs:
              credentialsOption: 'serviceEndpoint'
              serverEndpoint: '$(qaFtp)'
              rootDirectory: '$(Pipeline.Workspace)/$(webArtifactName)'
              filePatterns: '**'
              remoteDirectory: '/'
              clean: false
              cleanContents: false
              preservePaths: true
              trustSSL: false
