name: '$(BuildID).$(date:yyMMdd)'

trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  artifactName: chia-wallet
  versionNumber: '0.1.$(Build.BuildNumber)'
  qaEnvironment: 'chiabee_wallet_qa'
  qaFtp: 'chiabee_wallet_dev_ftp'

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - task: CmdLine@2
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        script: 'yarn'
      displayName: 'yarn'

    - task: CmdLine@2
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        script: |
          sed -i 's/0.0.0.0/$(versionNumber)/' .env.production
      displayName: 'set version'

    - task: CmdLine@2
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        script: 'yarn build'
      displayName: 'yarn build'

    - task: CmdLine@2
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)'
        script: 'echo $(versionNumber)>$(Build.SourcesDirectory)/dist/version.txt'
      displayName: 'write version file'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/dist'
        ArtifactName: '$(artifactName)'
        publishLocation: 'Container'


- stage: qa
  displayName: qa
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn:
  - build
  jobs:
  - deployment: qadeploy
    displayName: qaDeploy
    timeoutInMinutes: 10
    cancelTimeoutInMinutes: 1
    environment: $(qaEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: FtpUpload@2
            inputs:
              credentialsOption: 'serviceEndpoint'
              serverEndpoint: '$(qaFtp)'
              rootDirectory: '$(Pipeline.Workspace)/$(artifactName)'
              filePatterns: '**'
              remoteDirectory: '/'
              clean: false
              cleanContents: false
              preservePaths: true
              trustSSL: false      
