version: '3'

services:
  coin_processor:
    build:
      context: ../
      dockerfile: ./server/Dockerfile
    ports:
      - "3030:3030"
    environment:
      - SHOW_LOG=true
      - PORT=3030
      - MAX_THREAD=1
