name: build-cli

on:
  workflow_run:
    workflows: [ci-chia-lib]
    types: [completed]
  push:
    branches:
      - master
    paths:
      - "cli/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - master
    paths:
      - "cli/**"
      - ".github/workflows/**"

env:
  VERSION: 0.3.${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: |
          yarn test:cli

      - name: Build
        run: |
          yarn build:cli

      - name: version
        run: |
          echo ${VERSION}>dist/cli/version.txt

      - uses: actions/upload-artifact@v3
        with:
          name: cli-package
          path: dist/cli
