name: ci-pawket-i18n

on:
  push:
    branches:
      - master
      - feat_action
    paths:
      - 'pawket/**'
  pull_request:
    branches:
      - master
      - feat_action
    paths:
      - 'pawket/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      
      - name: Install yarn
        run: npm -g i yarn
      
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: yarn
      
      - name: Build and Test
        run: |
          yarn check-i18n --ci
