name: Deploy
on:
  workflow_dispatch: {}
  workflow_run:
    workflows: [build-pawket]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: mixch

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
