name: deploy-mixch
on:
  workflow_dispatch: {}
  workflow_run:
    workflows: [build-pawket]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: github.event.workflow_run.conclusion == 'success'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: mixch
          workflow: build-pawket.yml

      - uses: actions/upload-artifact@v3
        with:
          name: mixch
          path: .

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
